### PR TITLE
feat (switch): add support for the lifx switch

### LINKED ISSUE #38: [Feature Request] add support for LIFX Switch
Any chance to get support for the LIFX Switch?

### PR DESCRIPTION
**Pull request by bradrees**
This PR adds support for the Lifx Switch.

I've added tests and tested on my switches at home, and it all seems to work. 

Thanks to the work done by @Shakesbeard and @ristomatti  

Resolves #38

### CODE REVIEW

**Comment by ristomatti** [comment]
Thank you for the contribution! I'm very busy at the moment (working on a huge and blocker code refactor at work) so I can't promise when I will be able to review this. I'll be snoozing the email notification until I get time to properly check this.

I did a quick glance though and it seemed the changes seem to align with the codebase. Only biggest issue is about how well this fits to the current API.  A switch/relay cannot easily be seen as a light (even though it _could_ be toggling a light).

It would help if you could either:

- Update the README, while trying to figure out how to describe the new API in a way it doesn't sound awkward
- Come up with a suggestion how we could adapt the code structure to have an object **device** which would then be inherited by **light** and **switch** (or **relay**).

The latter would be preferred but as it'd be a lot of work, I'm not sure if I want it to be a thing to prevent people from using the library with their switches.

**Comment by ristomatti** [comment]
Just to update - I've not forgot about this. :grimacing:

**Comment by bradrees** [comment]
Hi, I have added some documentation and have been using this with Homebridge for the last 7 or so months, it works really well and is a big improvement over the standard lifx app. It's all stable and works every time.

It would be great to get this merged in, it really improves my setup at home.

Thanks!

**Review by ristomatti — APPROVED** [review]
Can't test this but can't spot any issues either. The code and docs fit nicely in the existing code style :+1:. I'll take a leap of faith and publish a new minor release. Thanks you for the contrib and sorry it took ages to review!

**Pull request merged**
