### PR TITLE
remove of deprected "new Buffer"

### PR DESCRIPTION
**Pull request by mabels**
Please integrated these first in preparation of the TileAPI.
This is only a cleanup of a deprecated api.

### CODE REVIEW

**Comment by Sawtaytoes** [comment]
Looks good to me!

**Comment by Sawtaytoes** [comment]
I just realized we might want to ensure the minimum Node.js version is correct for this change.

**Comment by mabels** [comment]
I think we should skip it, it since:
https://nodejs.org/docs/latest-v4.x/api/buffer.html

**Comment by Sawtaytoes** [comment]
Perfect.
👍

**Pull request merged**
