### PR TITLE
Update outdated dependencies

### PR DESCRIPTION
**Pull request by fkistner**
Brings all dependencies up-to-date and removes a bunch that should no longer be necessary.
Since we use some es2015, required node version is now likely 8.10 (verified with node v8.17.0), but that seems old enough that it shouldn't be an issue for most people.

```
$ npm audit
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
 in 1087 scanned packages
```

### CODE REVIEW

**Comment by ristomatti** [comment]
@fkistner Thank you for contributing! These changes require some consideration though. node-lifx supported pretty old node versions and some might be using it as part of some archaic home automation system for example. I would like to keep this as much a drop-in replacement for the time being unless someone convinces no versions prior to 8 are running this.

If it's OK to you, I'll leave this open and tag it in some way.

**Review by ristomatti — COMMENTED** [review]
Skimmed through the changes. A welcome cleanup and everything looks proper. Unfortunately this just needs to sit for a while. It'd require a major version change IMO to drop support for older node versions. @Sawtaytoes what do you think?

**Comment by ristomatti** [comment]
@fkistner You've likely forgotten this already but anyhow, I've rebased the changes, merged them, upgraded all dependencies yet again and published v2.0.0 to npm. :sweat_smile: 

There should now be no audit issues. I'll close the PR.

**Comment by Sawtaytoes** [comment]
Major version bump sounds fine to me.

**Comment by ristomatti** [comment]
It's my understanding of the semver practise when dropping existing features or platforms anyway. Well, now it's done anyway. So far no flood off issue reports at least. :joy:

**Pull request closed without merging**
