### PR TITLE
Merging Ristomatti's changes + outstanding PRs from node-lifx

### PR DESCRIPTION
**Pull request by Sawtaytoes**

### CODE REVIEW

**Comment by ristomatti** [comment]
Awesome! Sorry for not reacting faster as I was super busy over the weekend. Thank you for inviting to the organization.

I'm wondering if it would make sense to make a fork from the original repository instead though? I would still like to believe @MariusRumpf could pass on the npm package ownershi/publishing rights. There shouldn't be any limitation on publishing the package under a different name meanwhile?

**Comment by Sawtaytoes** [comment]
From what I've seen, you can publish whatever to npm. So if we need to publish a `0.8.0`, we can pull that that commit, tag it, and push it to npm.

**Comment by ristomatti** [comment]
What I meant is that this repo could also be a GitHub fork directly from node-lifx repo and use the same name. :)

**Comment by Sawtaytoes** [comment]
I see what you mean now. I copied it because it gives us more privileges. Forking the repo reduces what comes through. Since we're taking it over, I figure this is the best way. Also, this name will match the npm package I'll be publishing.

**Comment by ristomatti** [comment]
@Sawtaytoes Sorry for the long delay again (Midsummer celebration weekend here in Finland).

I kind of understand what you are after with this but have you considered that when you fork a repo, it will be shown in the Insights > Network section. This could help current users of node-lifx find the repo and also be convinced the intention is to continue where @MariusRumpf left. If you check the graph now, you'll find https://github.com/fkistner/node-lifx has been forked from my repo and apparently @fkistner has decided to drop dependency to Babel and I assume then only support newer versions of node. Regardless, I see a benefit in the forking approach. Like said, it doesn't prevent creating an npm package with a different name.

I would also suggest to stop and think about the name of the new package if the intention is to continue the work and stay backward compatible (to the extent it makes sense). Since current node-lifx version is 0.8.x but it's clearly been worthy of 1.x.x for a long time ago. I would suggest using a name directly making it obvious this package would be an uprade to the existing version. Perhaps just something as simple as `node-lifx-v2` or `lifx-lan`?

**Comment by Sawtaytoes** [comment]
## Forking
Hmm... I always see forks as illegitimate or personal projects. I would need to see a few major projects forked from others that are successful. I get that GitHub has link-backs, but we can update the README pointing people to the new one just like other major projects like RxJS:

- **Old:** https://github.com/Reactive-Extensions/RxJS
- **New:** https://github.com/ReactiveX/RxJS

For instance, RxJS moved their repo to a new location for v5 and on. They didn't fork the old one, they created a brand new one. Since the original author isn't supporting node-lifx anymore, we're doing the same thing as they did except we're not changing the API so previous compatibly will remain.

## Naming
I thought about using `v2` in the name, but then it would be like `apache2` or `Angular 2`. Very confusing for users.

`lifx-lan` is a nice name. I'd only need to rename the repo, and we'd be set. My only concern is making it difficult to pick-out on npm. It will be pretty confusing seeing `node-lifx`, `node-lifx-lan`, and `lifx-lan`.

Maybe we could just call it `lan` since the org is named `node-lifx`, and I will upload it under an npm org named `node-lifx`. That way, it would be `@node-lifx/lan`. Or we could do like you said: `@node-lifx/lifx-lan`.

What do you think?

**Comment by ristomatti** [comment]
You've convinced me that clean slate fork is ok and maybe even more appropriate since there's no intention to do PR's back. The name thing is still something that IMO would need a change. I agree `node-lifx-v2` would not be good for the reasons you mentioned but also it would kind of lock into a specific main version forever.

My suggestions yesterday were more to start the discussion anyway. Your suggestion on the org namespaced package is quite clever but I think such a short name would only make sense if the library was split into modules in some way. There's also a npm package with the name `lan` so it might confuse further. I would at this point vote for keeping things simple and publish a simple package name w/o org prefix.

Although `lifx-lan` initially felt like a decent name it's not without it's issues now when I think about it. The biggest one is that it sounds too similar to `node-lifx-lan` which is the "competing" library. If I remember correctly it was written without knowledge of `node-lifx` already existing.

It's obvious the name needs to have `lifx` in it for people to find it.

What would you think about `lifx-lan-client`? It would clearly indicate:
- it's related to LIFX
- it's not yet another LIFX cloud package
- it's a client, requiring further coding to make use of it

Making it's purpose clear already in the package name would also better allow differentiating it from possible further LIFX related repos. I've for example written a package called `lifxsh` which is an interactive shell utilising `node-lifx`. I haven't had time to improve it in years but still often use it when I'm at the computer.

I also think having `node` in the package name is redundant and probably mainly used if a name without `node-` prefix was already taken. As a GitHub org name it still makes a lot of sense and would help in making the connection between `node-lifx`.

**Comment by Sawtaytoes** [comment]
`lifx-lan-client` is good for me. Heck, you use `new LifxClient()` when you use it anyway.

I'll go ahead with that name.

**Comment by ristomatti** [comment]
> Heck, you use new LifxClient() when you use it anyway.

Exactly what I was thinking but forgot to mention! Could you change the repo name also?

And how do we go on from now? Since you were the initiator to this, I guess you call the shots. I would have some suggestions though in case you're open to some of them also: 

Like already mentioned previously I don't know yet how much actual development time I can put on this at the moment but I would be more happy to do code reviews as I am a strong believer in code reviews and don't think any changes should be done directly to `master` without anyone taking a second look or doing a test run.

I think a separate `dev` branch was not the best way to do changes/experimentation which seemed to be the way for node-lifx originally. Instead the changes should be done in separate feature/experintation branches and then merged to master through PR'S. And naturally when publishing to npm the code should be tagged with the new npm version.

Another thing I would suggest is adding a project view (it could be visible only to member) to discuss planned refactorings and/or breaking changes for example.

One other reason that has contributed to my lack of interest to develop node-lifx further is the fact that during the last 3 years I've moved away from Babel and now primarily use TypeScript (initially at work but nowadays also for personal projects which I often then run using ts-node to avoid the compilation step).

While doing the last changes to node-lifx I found myself other having trouble understanding what kind of data some of the functions is handling. There's some weird mutation done on the packets I had a had time following. It's one of the reasons I added the TSD file which is now included in this version.

A separate definition file is just a pain to keep up to date when the code itself is written in JS, and some of it is just based on the JSDoc from the code, so it's not nearly as good as I would like it to be.

@Sawtaytoes Would you by any chance be interest in developing this using TypeScript? If you would, I'd love to attempt to do the refactoring. I claim that after that, making improvements/bug fixes and especially refactoring the code would be a lot easier and most of all safer to do.

For most parts the codebase has pretty good unit test coverage which helped a lot in doing the ES2015 refactoring I did "some time ago".

I am on summer vacation for the next 5 weeks so I should be able to respond faster during that time and might be able to do some coding also. For example the suggested TS conversion could be interesting enough to spend vacation time on. :) 

Edit: Apparently I fell asleep yesterday while writing the reply on my phone and had accidentally submitted this midway. :D

**Comment by ristomatti** [comment]
@Sawtaytoes I noticed you've already changed the repo name which I asked on my previous comment. If you did it based on that, please read my comment again since I've now added the missing part but also added/edited other parts of it as it was submitted by accident.

**Comment by Sawtaytoes** [comment]
I don't mind having you do reviews. I made a few simple documentation changes to get this pushed up to npm, but other than that, I'm right on with using feature branches. Having an on-going dev branch just creates more merge conflicts and trouble.

I've actually never used TypeScript outside of one test project and don't have any tooling setup to handle it. If you wanna do a TypeScript refactor, I have no arguments. I know it's been in fashion recently, but I wouldn't be able to help out early-on.

I get that mutations are problematic when working on other peoples' code. If the codebase is difficult to update, maybe we modular it instead. We'd think in terms of components, and separate everything out so it could be reworked independently.

**Comment by fkistner** [comment]
Great to see, there's continued activity on this! 😃
For reference, I finally got around to cleaning up my changes and rebased them on this repo, see node-lifx/lifx-lan-client#29.

**Pull request merged**
