### PR TITLE
Add opts for discovery interval and message rate limit

### PR DESCRIPTION
**Pull request by justfalter**
- Adds `discoveryInterval` and `messageRateLimit` to client.init

### CODE REVIEW

**Comment by Sawtaytoes** [comment]
This looks good to me. I'm adding Ristomatti as he'll know more about the underlying architecture.

**Comment by ristomatti** [comment]
@justfalter Thanks, this looks great! Would you mind updating the README also? Or could you @Sawtaytoes do that after merging?

**Review by ristomatti — APPROVED** [review]
Code looks fine but please see my earlier comment.

**Comment by justfalter** [comment]
Updated the README and wording in the jsdoc. Also added unit tests (I somehow missed pushing these, yesterday).

**Comment by ristomatti** [comment]
Great work, thanks!

**Pull request merged**
