### PR TITLE
Add light.waveform

### PR DESCRIPTION
**Pull request by domdomegg**
Adds [setWaveform](https://lan.developer.lifx.com/docs/light-messages#section-setwaveform-103) support

### CODE REVIEW

**Review by ristomatti — COMMENTED** [review]
This looks good and straightforward. Would you mind updating the README.md also?

**Comment by ristomatti** [comment]
@domdomegg Thanks! I'll try to find time to test this over the weekend.

It's worth noting that while I'm indrectly using this library every day (as a Node-RED plugin), I haven't worked much at all with the codebase for a couple of years. So please share if you happen to have some snippet of code to quickly test this on a light.

**Comment by domdomegg** [comment]
> It's worth noting that while I'm indrectly using this library every day (as a Node-RED plugin), I haven't worked much at all with the codebase for a couple of years. So please share if you happen to have some snippet of code to quickly test this on a light.

Unfortunately I can't share my full usage of this publicly yet, but here's a quick snippet for it I've whipped up:

(checkout the branch, run `npm run build`, place this in the root folder and run `node waveformsnippet.js`)

```js
const LifxClient = require('./lib/lifx').Client;
const client = new LifxClient();

const wait = (ms) => () => new Promise((resolve) => setTimeout(resolve, ms));

client.on('light-new', (light) => {
  Promise.resolve()

    // Set to white
    .then(light.color(0, 0, 100))
    .then(wait(500))

    // Do red saw wave
    .then(() => light.waveform(0, 100, 100))
    .then(wait(4000))

    // Set to white (stops wave)
    .then(() => light.color(0, 0, 100))
    .then(wait(500))

    // Do five 1-second cycles of green, non-transient (returning to white)
    .then(() => light.waveform(120, 100, 100, 3500, false, 1000, 5, 0.5, 1))
    .then(wait(100)) // only need to wait long enough for the command to be sent

    .then(() => client.destroy());
});

client.init();
```

**Comment by ristomatti** [comment]
Thanks! Exactly what I was after.

**Comment by ristomatti** [comment]
Just a quick follow up. Sorry I've left this hanging! I've been sick and only barely coping with daily (closed source) work. I've got this tab open as reminder so eventually I'll get to this. I'm 99% certain there's no issues with your code but with LIFX firmware being flaky at times I believe it makes sense to double check a change. Especially as we'll then get bug reports if it isn't working. I hope you understand.

**Comment by domdomegg** [comment]
No problem at all, it's not urgent - I have a private fork for use in my projects already, just figured I'd contribute this upstream to be useful to others.

Totally understanding the need to thoroughly check changes, I definitely don't want to be introducing bugs. And please prioritize your main work over this, and health over everything!

**Comment by ristomatti** [comment]
Sorry it took ages but finally tested it and I'm happy to say it works as described. Great work and thank you for the contribution!

**Comment by ristomatti** [comment]
...and it's published with version 1.0.4.

**Comment by domdomegg** [comment]
> Sorry it took ages but finally tested it and I'm happy to say it works as described. Great work and thank you for the contribution!

No problem about the delay :) Thanks for the review!

**Pull request merged**
